# Generated by Django 2.1.3 on 2018-11-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_shop_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='image',
        ),
    ]
