# Generated by Django 2.1.3 on 2018-11-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_flower_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='city_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='shop',
            new_name='shop_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
