# Generated by Django 2.1.3 on 2018-11-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181126_0547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shop',
            new_name='shop_id',
        ),
    ]
