# Generated by Django 2.1.3 on 2018-11-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181126_0548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderflower',
            old_name='flower',
            new_name='flower_id',
        ),
        migrations.RenameField(
            model_name='orderflower',
            old_name='order',
            new_name='order_id',
        ),
    ]
